# Generated by Django 5.1.4 on 2024-12-14 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postSite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='post',
            name='create_datetime',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
